VolleyballKlassementView/src/main/java/controllers/ClubController.java
package controllers;

import java.io.Console;
import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

/**
 *
 * @author demun
 */
@Named
@ApplicationScoped
public class ClubController implements Serializable {
    private String competitieNaam;
    private String regio;
    private String divisie;
    private String club;
    private String teamNaam;
    
     @PostConstruct
    public void init() {
        competitieNaam = "vb 1ste divisie";
        regio = "vlaams-brabant";
        divisie = "1ste divisie";
        club= "davoc lot";
        teamNaam = "davoc lot heren1";
    }
    
   

    public String getCompetitieNaam() {
        return competitieNaam;
    }

    public void setCompetitieNaam(String competitienaam) {
        this.competitieNaam = competitienaam;
    }

    public String getRegio() {
        return regio;
    }

    public void setRegio(String regio) {
        this.regio = regio;
    }

    public String getDivisie() {
        return divisie;
    }

    public void setDivisie(String divisie) {
        this.divisie = divisie;
    }

    public String getClub() {
        return club;
    }

    public void setClub(String club) {
        this.club = club;
    }

    public String getTeamNaam() {
        return teamNaam;
    }

    public void setTeamNaam(String teamNaam) {
        this.teamNaam = teamNaam;
    }
    
    
    
}

VolleyballKlassementView/src/main/java/controllers/CompetitionController.java
package controllers;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

@Named
@ApplicationScoped
public class CompetitionController implements Serializable {
    private String name;
    private String division;
    private String region;
    //vergeet niet dit naar de klassen te zetten
    private List<String> teamList;
    private List<String> GameList;
    
    @PostConstruct
    public void init(){
        name = "vb-1ste divisie";
        division = "1ste divisie";
        region = "Vlaams-Brabant";
        teamList = new ArrayList<>();
        teamList.add("davoc lot");
        teamList.add("keerberen");
        teamList.add("leuven");
        
        GameList = new ArrayList<>();
        GameList.add("game1");
        GameList.add("game2");
        GameList.add("game3");
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDivision() {
        return division;
    }

    public void setDivision(String division) {
        this.division = division;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public List<String> getTeamList() {
        return teamList;
    }

    public void setTeamList(List<String> teamList) {
        this.teamList = teamList;
    }

    public List<String> getGameList() {
        return GameList;
    }

    public void setGameList(List<String> GameList) {
        this.GameList = GameList;
    }
    
    
    
}

VolleyballKlassementView/src/main/java/controllers/GameController.java
package controllers;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

@Named
@ApplicationScoped
public class GameController implements Serializable{
    private String plaats;
    //vergeet niet naar klasse te veranderen.
    private String thuisPloeg;//*
    private String uitPloeg;//*
    private String competition;//*
    private Date gameDate;
    private Integer resultaatThuisploeg;
    private Integer resultaatUitploeg;
    
    
    @PostConstruct
    public void init(){
        thuisPloeg = "davoc lot";
        uitPloeg = "leuven";
        competition = "vb-1ste divisie";
        gameDate = new Date();
        resultaatThuisploeg = 3;
        resultaatUitploeg = 0;
    }

    public String getPlaats() {
        return plaats;
    }

    public void setPlaats(String plaats) {
        this.plaats = plaats;
    }

    public String getThuisPloeg() {
        return thuisPloeg;
    }

    public void setThuisPloeg(String thuisPloeg) {
        this.thuisPloeg = thuisPloeg;
    }

    public String getUitPloeg() {
        return uitPloeg;
    }

    public void setUitPloeg(String uitPloeg) {
        this.uitPloeg = uitPloeg;
    }

    public String getCompetition() {
        return competition;
    }

    public void setCompetition(String competition) {
        this.competition = competition;
    }

    public Date getGameDate() {
        return gameDate;
    }

    public void setGameDate(Date gameDate) {
        this.gameDate = gameDate;
    }

    public Integer getResultaatThuisploeg() {
        return resultaatThuisploeg;
    }

    public void setResultaatThuisploeg(Integer resultaatThuisploeg) {
        this.resultaatThuisploeg = resultaatThuisploeg;
    }

    public Integer getResultaatUitploeg() {
        return resultaatUitploeg;
    }

    public void setResultaatUitploeg(Integer resultaatUitploeg) {
        this.resultaatUitploeg = resultaatUitploeg;
    }
    
}

VolleyballKlassementView/src/main/java/controllers/PlayerController.java

import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;


@Named
@ApplicationScoped
public class PlayerController implements Serializable{
    private String firstName = "Jelter";
    private String lastName = "Demunter";
    private String dateOfBirth = "1996-08-06";
    private String team_id = "1000";

//    public String player() {
//        return "player.xhtml";
//    }
     @PostConstruct
    public void init() {
         System.out.println("in init methode");
       firstName = "Jelter";
       lastName = "Demunter";
       dateOfBirth = "1996-08-06";
       team_id = "1000";
    }
    
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(String dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getTeam_id() {
        return team_id;
    }

    public void setTeam_id(String team_id) {
        this.team_id = team_id;
    }
    
    
}

VolleyballKlassementView/src/main/java/controllers/TeamController.java
package controllers;

import java.util.ArrayList;
import java.util.List;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

@Named
@ApplicationScoped
public class TeamController {
    private String name;
    private List<String> playerList;
    //vergeet dit niet om naar klassen te doen
    private String club;
    private String competition;
    
    public void init(){
        name = "davoc lot heren 1";
        playerList = new ArrayList<>();
        playerList.add("Jelter");
        playerList.add("kevin");
        playerList.add("joren");
        club = "davoc lot";
        competition = "1ste divisie";
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<String> getPlayerList() {
        return playerList;
    }

    public void setPlayerList(List<String> playerList) {
        this.playerList = playerList;
    }

    public String getClub() {
        return club;
    }

    public void setClub(String club) {
        this.club = club;
    }

    public String getCompetition() {
        return competition;
    }

    public void setCompetition(String competition) {
        this.competition = competition;
    }
    
}

VolleyballKlassementView/src/main/webapp/ClubCreate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Title</title>
    </h:head>
    <h:body>

        <b:navBar brand="Volleyball Klassement" brandHref="#" inverse="true">
            <b:navbarLinks pull="right">
                <b:navLink span="10"></b:navLink>
                <b:navLink value="Home" href="index.xhtml"></b:navLink>
                <b:navLink value="Link" href="ClubCreate.xhtml"></b:navLink>
                <b:navLink value="competition" href="Competitions.xhtml"></b:navLink>
            </b:navbarLinks>
        </b:navBar>  

        <b:form style="margin-left: 9.5%">
            <b:row>
                <b:column span="4">
                    <h:outputText value="competitieNaam : "/>
                    <b:inputText id="competitieNaam" value="#{clubCreateController.competitieNaam}"/>
                </b:column>
            </b:row>
            <b:row>
                <b:column span="4">
                    <h:outputText value="regio : "/>
                    <b:inputText styleClass="form-control" value="#{clubCreateController.regio}"/>
                </b:column>
            </b:row>
            <b:row>
                <b:column span="4">
                    <h:outputText value="divisie : "/>
                    <b:inputText styleClass="form-control" value="#{clubCreateController.divisie}"/>
                </b:column>
            </b:row>
            <b:row>
                <b:column span="4">
                    <h:outputText value="club : "/>
                    <b:inputText styleClass="form-control" value="#{clubCreateController.club}"/>
                </b:column>
            </b:row>
            <b:row>
                <b:column span="4">
                    <h:outputText value="teamnaam : "/>
                    <b:inputText styleClass="form-control" value="#{clubCreateController.teamnaam}"/>
                </b:column>
            </b:row>
            <b:commandButton value="zoeken" look="primary" style="margin-left: 9.5%"></b:commandButton>

        </b:form>


    </h:body>
</html>

VolleyballKlassementView/src/main/webapp/Competition.xhtml
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui"

      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>TODO supply a title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    </h:head>
    <h:body>

        <b:navBar brand="Volleyball Klassement" brandHref="#" inverse="true">
            <b:navbarLinks pull="right">
                <b:navLink span="10"></b:navLink>
                <b:navLink value="Home" href="index.xhtml"></b:navLink>
                <b:navLink value="Link" href="ClubCreate.xhtml"></b:navLink>
                <b:navLink value="competition" href="Competitions.xhtml"></b:navLink>
            </b:navbarLinks>
        </b:navBar>
        <b:container>
            <b:column span="5">
        <b:form horizontal="true">
            <h1 style="margin-left: 3%">competitions</h1>
            <ul style="width: 40%">

                <li class="list-group-item"><span class="font-weight-bold">name : </span><h:outputText
                        value="#{competitionController.name}"/></li>
                <li class="list-group-item"><span class="font-weight-bold">division : </span><h:outputText
                        value="#{competitionController.division}"/></li>
                <li class="list-group-item"><span class="font-weight-bold">region : </span><h:outputText
                        value="#{competitionController.region}"/></li>
                <li class="list-group-item"><span class="font-weight-bold">teams : </span><h:outputText
                        value="#{competitionController.teamList}"/></li>

            </ul>
             <b:formGroup>
                    <b:selectOneMenu value="#{teamController.name}" colMd="2" required="true" label="lijst bestaande teams:" labelColMd="2">
                        <f:selectItem itemLabel="(Please select)" itemValue="" />
                        <f:selectItem itemLabel="davoc lot" itemValue="1" />
                        <f:selectItem itemLabel="leuven" itemValue="2" />
                        <f:selectItem itemLabel="keerbergen" itemValue="3" />
                    </b:selectOneMenu>
                    <b:message for="@previous" colMd="2" />
                </b:formGroup>
            <b:commandButton value="voeg een team toe" look="primary" style="margin-left: 3%"></b:commandButton>
        </b:form>
        </b:column>
            <b:column span="5">
        <b:form>
            <h1 style="margin-left: 3%">wedstrijden</h1>
            <b:commandButton value="filter" look="primary" style="margin-left: 3%"></b:commandButton>
            <ul style="width: 40%">
                <li class="list-group-item"><span class="font-weight-bold">games : </span><h:outputText
                        value="#{competitionController.gameList}"/></li>
            </ul>
            <b:commandButton value="voeg een wesrtijd toe" look="primary" style="margin-left: 3%"></b:commandButton>
        </b:form>
                </b:column>
        </b:container>
        <b:button value="klassement" href="klassement.xhtml"></b:button>




    </h:body>
</html>

VolleyballKlassementView/src/main/webapp/Competitions.xhtml
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui"
      >
    <h:head>
        <title>TODO supply a title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    </h:head>
    <h:body>

        <b:navBar brand="Volleyball Klassement" brandHref="#" inverse="true">
            <b:navbarLinks pull="right">
                <b:navLink span="10"></b:navLink>
                <b:navLink value="Home" href="index.xhtml"></b:navLink>
                <b:navLink value="Link" href="ClubCreate.xhtml"></b:navLink>
                <b:navLink value="competition" href="Competitions.xhtml"></b:navLink>
            </b:navbarLinks>
        </b:navBar>  

        <h1 style="margin-left: 3%">competitions</h1>
        <ul>

            <li class="list-group-item"><span class="font-weight-bold">name : </span><h:outputText
                    value="#{competitionController.name}"/></li>
            <li class="list-group-item"><span class="font-weight-bold">division : </span><h:outputText
                    value="#{competitionController.division}"/></li>
            <li class="list-group-item"><span class="font-weight-bold">region : </span><h:outputText
                    value="#{competitionController.region}"/></li>
            <li class="list-group-item"><span class="font-weight-bold">teams : </span><h:outputText
                    value="#{competitionController.teamList}"/></li>
            <li class="list-group-item"><span class="font-weight-bold">games : </span><h:outputText
                    value="#{competitionController.gameList}"/></li>

        </ul>
        <b:button value="voeg een competitie toe" look="primary" style="margin-left: 3%"></b:button>
    </h:body>
</html>

VolleyballKlassementView/src/main/webapp/WEB-INF/templates/template.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
>
<h:head>
    <title><ui:insert name="pageTitle"/></title>
</h:head>
<body>
<!--<h:navBar brand="Brand" brandHref="#" inverse="true">-->
<!--</b:navBar>-->
<!--<b:container fluid="true">-->
    <ui:insert name="pageContent"/>
<!--</b:container>-->
</body>
</html>

VolleyballKlassementView/src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:b="http://bootsfaces.net/ui">
    <h:head>
        <title>Title</title>
    </h:head>
    <h:body>

        
        <b:navBar brand="Volleyball Klassement" brandHref="#" inverse="true">
            <b:navbarLinks pull="right">
                <b:navLink span="10"></b:navLink>
                <b:navLink value="Home" href="index.xhtml"></b:navLink>
                <b:navLink value="Link" href="ClubCreate.xhtml"></b:navLink>
                <b:navLink value="competitions" href="Competitions.xhtml"></b:navLink>
                <b:navLink value="competition" href="Competition.xhtml"></b:navLink>
            </b:navbarLinks>
        </b:navBar>  

        <b:container>
            <b:column span="5">
                <p>
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
                    when an unknown printer took a galley of type and scrambled it to make a type
                    specimen book. It has survived not only five centuries, but also the leap into
                    electronic typesetting, remaining essentially unchanged. It was popularised in
                    the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
                    and more recently with desktop publishing software like Aldus PageMaker including
                    versions of Lorem Ipsum.
                </p>
            </b:column>
            <b:column span="5">
                <p>
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
                    when an unknown printer took a galley of type and scrambled it to make a type
                    specimen book. It has survived not only five centuries, but also the leap into
                    electronic typesetting, remaining essentially unchanged. It was popularised in
                    the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
                    and more recently with desktop publishing software like Aldus PageMaker including
                    versions of Lorem Ipsum.
                </p>
            </b:column>
        </b:container>
        <b:button value="voeg een club toe" look="primary" style="margin-left: 9.5%"></b:button>


    </h:body>
</html>

VolleyballKlassementView/src/main/webapp/player.xhtml
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui"
      >
    <h:head>
        <title>TODO supply a title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    </h:head>
    <h:body>

        <b:navBar brand="Volleyball Klassement" brandHref="#" inverse="true">
            <b:navbarLinks pull="right">
                <b:navLink span="10"></b:navLink>
                <b:navLink value="Home" href="index.xhtml"></b:navLink>
                <b:navLink value="Link" href="ClubCreate.xhtml"></b:navLink>
                <b:navLink value="competition" href="Competitions.xhtml"></b:navLink>
            </b:navbarLinks>
        </b:navBar>  

        <h1>dit is de pagina player</h1>
        <ul>

            <li class="list-group-item"><span class="font-weight-bold">First name : </span><h:outputText
                    value="#{playerController.firstName}"/></li>
            <li class="list-group-item"><span class="font-weight-bold">Last name : </span><h:outputText
                    value="#{playerController.lastName}"/></li>
            <li class="list-group-item"><span class="font-weight-bold">Birth date : </span><h:outputText
                    value="#{playerController.dateOfBirth}"/></li>
            <li class="list-group-item"><span class="font-weight-bold">Team id : </span><h:outputText
                    value="#{playerController.team_id}"/></li>

        </ul>

    </h:body>
</html>